### ISSUE TITLE
Drones consuming containers drop the items to the floor

### ISSUE THREAD

**Issue by TobleroneSwordfish** [stonepillars/goon-flock#19] opened 2022-03-12 14:50 UTC
### Labels

[FEATURE]

### Description

^

### Steps to reproduce

1. Be drone
2. Pick up pill bottle and consume it
3. Pills drop everywhere forcing you to pick up each one individually

### Expected Behavior

It should probably work like the cages, where it consumes the contents first and then the container itself

**Comment by amylizzle** [comment] 2022-03-12 17:47
I'm not sure this is a bug, as this seems to be intended behaviour.

**Comment by stonepillars** [comment] 2022-03-15 12:33
This is how drones work so that the dumb drones can empty containers and munch on their contents.
However, eating the container's contents at the same time (at the penalty of time) could be a good solution

**Comment by amylizzle** [comment] 2022-04-02 17:09
I think we should close this, it's now explicitly intended behaviour.

**Comment by stonepillars** [comment] 2022-04-02 20:19
Intended

**Closed by stonepillars** 2022-04-02 20:19 UTC
Labels: wontfix
